[package]
name = "d2018"
version = "0.1.0"
publish = false
edition = "2021"
rust-version = "1.74"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.81"
daocutil = { version = "0.1.0", path = "../daocutil" }
itertools = "0.12.1"
nu-ansi-term = "0.50.0"
regex = "1.10.4"
thiserror = "1.0.58"
