[package]
name = "d2021"
publish = false
version = "0.1.0"
rust-version = "1.56.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
md5 = "0.7.0"
rayon = "1.7.0"
regex = "1.5.5"
thiserror = "1.0.30"

daocutil = { path = "../daocutil" }
