[package]
name = "d2017"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
daocutil = { path = "../daocutil" }
anyhow = "1.0.71"
thiserror = "1.0.43"
itertools = "0.11.0"
nu-ansi-term = "0.49.0"
