[package]
name = "d2017"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
daocutil = { path = "../daocutil" }
anyhow = "1.0.75"
thiserror = "1.0.50"
itertools = "0.11.0"
nu-ansi-term = "0.49.0"
