[package]
name = "d2017"
publish = false
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[lints]
workspace = true

[dependencies]
daocutil = { path = "../daocutil" }
anyhow = "1.0.81"
thiserror = "1.0.57"
itertools = "0.12.1"
nu-ansi-term = "0.50.0"
