[package]
name = "d2020"
publish = false
version = "0.1.0"
authors = ["Kristofer Rye <kristofer.rye@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
static_assertions = "1.1.0"

[workspace]
members = [
	"d2020-02",
	"d2020-03",
	"d2020-04",
	"d2020-05",
	"d2020-06",
]
