[package]
name = "d2020"
publish = false
version = "0.1.0"
authors = ["Kristofer Rye <kristofer.rye@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
num = "0.3.1"
num-integer = "0.1.44"
regex = "1.4.2"
thiserror = "1.0.24"

daocutil = { path = "../daocutil" }

[dev-dependencies]
static_assertions = "1.1.0"

[[bin]]
name = "day07"
path = "src/day07/main.rs"

[[bin]]
name = "day13"
path = "src/day13/main.rs"

[[bin]]
name = "day19"
path = "src/day19/main.rs"

[[bin]]
name = "day25"
path = "src/day25/main.rs"
