[package]
name = "d2022"
publish = false
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[lints]
workspace = true

[dependencies]
daocutil = { path = "../daocutil" }
anyhow = "1.0.76"
thiserror = "1.0.52"
itertools = "0.12.0"
nu-ansi-term = "0.49.0"
regex = "1.10.2"
