[package]
name = "d2022"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
daocutil = { path = "../daocutil" }
anyhow = "1.0.71"
thiserror = "1.0.40"
itertools = "0.11.0"
nu-ansi-term = "0.48.0"
regex = "1.9.1"
