[package]
name = "d2022"
publish = false
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[lints]
workspace = true

[dependencies]
daocutil = { path = "../daocutil" }
anyhow = "1.0.79"
thiserror = "1.0.56"
itertools = "0.12.1"
nu-ansi-term = "0.50.0"
regex = "1.10.3"
