name: Check and Test

on:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  check-rust:
    name: Check the code
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta]
    steps:
      - name: Install the appropriate Rust toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }} --component clippy,rustfmt
          rustup default ${{ matrix.rust }}
      - uses: actions/checkout@v5
      - name: Run rustfmt
        run: |
          cargo fmt --all -- --check
      - name: Run clippy
        run: |
          cargo clippy --workspace --all-features --all-targets

  test-rust:
    name: Test the code
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
    steps:
      - name: Install the appropriate Rust toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
      - uses: actions/checkout@v5
      - name: Run cargo test
        run: |
          cargo test --workspace --all-features --all-targets --no-fail-fast

  coverage-rust:
    name: Measure test coverage
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        rust: [stable]
    steps:
      - name: Install the appropriate Rust toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }} --component llvm-tools-preview
          rustup default ${{ matrix.rust }}
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov --version=0.5.0
      - uses: actions/checkout@v5
      - name: Run cargo-llvm-cov
        run: >
          cargo llvm-cov
          --all-features
          --all-targets
          --workspace
          --lcov
          --output-path lcov.info
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - uses: actions/upload-artifact@v4
        with:
          name: lcov.info
          path: ./lcov.info