[package]
name = "d2016"
version = "0.1.0"
publish = false
edition = "2021"
rust-version = "1.74"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.76"
daocutil = { version = "0.1.0", path = "../daocutil" }
itertools = "0.12.1"
nu-ansi-term = "0.49.0"
regex = "1.10.2"
thiserror = "1.0.52"
